; LAb 04

EXTRN INPUT_MATRIX: NEAR
EXTRN OUT_MATRIX: NEAR
EXTRN OUTPUT_SYM: NEAR
EXTRN REPLACE_SPACE: NEAR
EXTRN MATRIX_PROCESS: NEAR

PUBLIC MAT
PUBLIC ROW_NUM
PUBLIC COL_NUM
PUBLIC COL_INDEX

;khai baos stack segment
SSTK SEGMENT PARA STACK 'STACK'
	db 200h dup(0)
SSTK ENDS

;khai baos data segment
DATAS SEGMENT PARA PUBLIC 'DATA'
	MAT db 81 dup(1)
	ROW_NUM db 3
	COL_NUM db 3
	COL_INDEX db 0
	
DATAS ENDS

CODES SEGMENT PARA PUBLIC 'CODE'
	ASSUME CS:CODES, DS:DATAS
	
main:
	mov ax, DATAS
	mov DS, ax

	call INPUT_MATRIX
	call OUT_MATRIX
	call MATRIX_PROCESS
	call OUT_MATRIX
	
	END_MAIN:
		mov ax, 4C00h
		int 21h
	
CODES ENDS
END main